name: MSBuild
on: push
jobs:
  build:
    name: MSBuild
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup Nuget
      uses: NuGet/setup-nuget@v1.2.0

    - name: Restore nuget packages
      run: nuget restore AtsExCsTemplate.sln

    - name: MSBuild
      run: msbuild AtsExCsTemplate.sln -property:Configuration=Release
      shell: cmd

    - name: Check dir
      run: tree /f
      shell: cmd

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-result
        path: ./msbuild_actions_sample/out/
