name: MSBuild
on: push
jobs:
  build:
    name: MSBuild
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup Nuget
      uses: NuGet/setup-nuget@v1.2.0

    - name: Restore nuget packages
      run: nuget restore AtsExCsTemplate.sln

    - name: MSBuild
      run: msbuild AtsExCsTemplate.sln /m /p:configuration="Release" /p:platform="Any CPU" /p:OutputPath="./out/"
      shell: cmd

    - name: Serch and move artifact
      run: |
        ls -alR
        mkdir out/
        find . -type f -path '**bin**.dll' | xargs mv -t ./out/
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: plugins
        path: ./out/
