name: Create release
on:
   workflow_dispatch:
   push:
   pull_request:
     branches:
       - main
     types:
       - closed
env:
   VERSION: 0

jobs:
  build:
    name: Generate dll
    runs-on: windows-latest
    outputs:
      NAME: ${{ steps.version.outputs.name }}
      VERSION: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.3.1
      - name: Setup Nuget
        uses: NuGet/setup-nuget@v1.2.0
      - name: Restore nuget packages
        run: nuget restore AtsExCsTemplate.sln
      - name: Build sln
        run: msbuild AtsExCsTemplate.sln /m /p:configuration="Release" /p:platform="Any CPU" /p:OutputPath="./out/"
        shell: cmd
      - name: Collect artifact
        run: |
          mkdir plugins/
          find . -type f -path '*/out/*.dll' | xargs mv -t ./plugins/
        shell: bash
      - name: Check assembly version
        id: version
        run: |
          Get-ChildItem plugins/ -Recurse -Filter "*.dll" -File | foreach {
          Write-Output $_.FileName
          $_.FileName
          #echo "::set-output name=name::$_"
          echo "name=$_" >> $GITHUB_OUTPUT
          $ver=(Get-Item $_.FullName).VersionInfo.FileVersion
          $ver
          #echo "::set-output name=version::$ver"
          echo "=v$ver" >> $GITHUB_OUTPUT
          }
        shell: pwsh
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: plugins
          path: ./plugins/
  tag:
    name: Create tag
    runs-on: ubuntu-latest
    needs: build
    #if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.2
      - name: Install exiftool
        run: |
           sudo apt update
           sudo apt install exiftool
      - name: Check ver
        run: |
           ls -alR
           find plugins/ -name '*.dll' | xargs -i exiftool -FileVersion -ProductVersion {}
      - name: Check versions
        run: |
           find plugins/ -name '*.dll | xargs readlink
           find plugins/ -name '*.dll | xargs -i exiftool -FileVersion -ProductVersion {}
          #for file in `find plugins/ -name '*.dll'`; do readlink $file; exiftool -FileVersion -ProductVersion $file; done
      - name: Check outputs
        run: |
           echo ${{needs.build.outputs.NAME}}
           echo ${{needs.build.outputs.VERSION}}
      - name: Checkout repository
        uses: actions/checkout@v4
