name: Create release
on:
   workflow_dispatch:
   push:
   pull_request:
     branches:
       - main
     types:
       - closed

jobs:
  build:
    name: Generate dll
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.3.1
      - name: Setup Nuget
        uses: NuGet/setup-nuget@v1.2.0
      - name: Restore nuget packages
        run: nuget restore AtsExCsTemplate.sln
      - name: MSBuild
        run: msbuild AtsExCsTemplate.sln /m /p:configuration="Release" /p:platform="Any CPU" /p:OutputPath="./out/"
        shell: cmd
      - name: Collect artifact
        run: |
          mkdir plugins/
          find . -type f -path '*/out/*.dll' | xargs mv -t ./plugins/
        shell: bash
      - name: Check assembly version
        run: |
          Get-ChildItem plugins/ -Recurse -Filter "*.dll" | foreach {
          Write-Output $_.FullName
          (Get-Item $_.FullName).VersionInfo.Comments
          }
        shell: pwsh
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: plugins
          path: ./plugins/
  tag:
    name: Create tag
    runs-on: ubuntu-latest
    needs: build
    #if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.2
      - name: check dir
        run: |
           ls -alR
           find plugins/ -name '*.dll' | xargs -i exiftool -FileVersion -ProductVersion {}
      - name: Checkout repository
        uses: actions/checkout@v4
